version: '3.2'
services:
  web:
    environment:
      db_user: ${db_user}
      db_host: ${db_host}
      db_name: ${db_name}
      db_table_prefix: ${db_table_prefix}
      server_port: ${server_port}
      logstash_addr: ${logstash_addr}
    
    build: .
    ports:
      - 80:80
    links:
      - db
      - logstash
      - kibana
      - elasticsearch
    depends_on:
      - db
      - logstash
  
  db:
    image: mongo:latest
    restart: always
    # environment:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    volumes:
      - type: bind
        source: ./conf/elk/elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  logstash:
    build:
      context: conf/elk/logstash/
    volumes:
      - type: bind
        source: ./conf/elk/logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./conf/elk/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    volumes:
      - type: bind
        source: ./conf/elk/kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  data: {}
  elasticsearch:
